#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# polybar

~/.config/polybar/launch.sh &


picom & 
feh --bg-fill ~/Pictures/wall/download.jpeg &
xrdb merge ~/.Xresources &
xinput set-prop 8 'libinput Accel Speed' -0.75 &
pulseaudio -D &
xsetroot -cursor_name left_ptr &
setxkbmap -layout us,ru -option 'grp:alt_shift_toggle' &
bash ~/fix_time.sh

bspc monitor HDMI-A-0 -d 1 2 3
bspc monitor DVI-D-0 -d 4 5 6 

bspc config border_width         1
bspc config window_gap          12
bspc config border_radius       8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle       true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# border colors
bspc config focused_border_color "#83a598"
bspc config normal_border_color "#454849"

#ignore_ewmh_fullscreen false

